version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_network

  backend:
    build: ./backend
    environment:
      - ENV=${ENV}
      - TOPIC_NAME=${TOPIC_NAME}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
    command: [ "gunicorn", "config.asgi:application", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000" ]
    networks:
      - backend_network

  frontend:
    build:
      context: ./frontend
      target: ${NODE_ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
      - VUE_APP_ENV=${ENV}
    ports:
      - "${FRONTEND_PORT}:${SERVER_FRONTEND_PORT}"
    depends_on:
      - backend
    networks:
      - frontend_network

volumes:
  postgres_data:


networks:
  frontend_network:
  backend_network:
