version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - ENV=${ENV}
      - TOPIC_NAME=${TOPIC_NAME}
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/app
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    depends_on:
      - db

  frontend:
    build: ./frontend
    environment:
      - VUE_APP_ENV=${ENV}
    ports:
      - "${FRONTEND_PORT}:8080"
    volumes:
      - ./frontend:/app
    # command: [ "npm", "run", "serve" ]
    depends_on:
      - backend

volumes:
  postgres_data:
