version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: django_admin
      POSTGRES_PASSWORD: admin@2
      POSTGRES_DB: mailassistantdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgres://django_admin:admin@2@db:5432/mailassistantdb
      - ENV=${ENV}
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/app 
      - /app/node_modules 
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db

  frontend:
    build: ./frontend
    environment :
      - VUE_APP_ENV=${ENV}
    ports:
      - "${FRONTEND_PORT}:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "serve"]
    depends_on:
      - backend

volumes:
  postgres_data:
