version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      - ENV=${ENV}
      - TOPIC_NAME=${TOPIC_NAME}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    command: ["uvicorn", "config.asgi:application", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: ./frontend
    environment:
      - VUE_APP_ENV=${ENV}
      - NODE_ENV=${NODE_ENV}
    ports:
      - "${FRONTEND_PORT}:8080"
    volumes:
      - ./frontend:/app
    command: [ "npm", "run", "serve" ]
    depends_on:
      - backend

volumes:
  postgres_data:
