services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - app_prod_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_network
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped

  backend_dev:
    build:
      context: ./backend
      target: development
    environment:
      - ENV=${ENV}
      - TOPIC_NAME=${TOPIC_NAME}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
    networks:
      - backend_network
    volumes:
      - ./backend:/app
      - /home/prod/prod/backend/media/pictures:/app/media/pictures
      - /home/prod/prod/backend/media/labels:/app/media/labels
    restart: unless-stopped

  backend_prod:
    build:
      context: ./backend
      target: production
    environment:
      - ENV=${ENV}
      - TOPIC_NAME=${TOPIC_NAME}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
    command: [ "gunicorn", "config.asgi:application", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000" ]
    networks:
      - backend_network
    volumes:
      - /home/prod/prod/backend/media/pictures:/app/media/pictures
      - /home/prod/prod/backend/media/labels:/app/media/labels
    restart: unless-stopped

  frontend_dev:
    build:
      context: ./frontend
      target: development
      args:
        VUE_APP_ENV: ${ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
      - VUE_APP_ENV=${ENV}
    ports:
      - "${FRONTEND_PORT}:${SERVER_FRONTEND_PORT}"
    depends_on:
      - backend_dev
    networks:
      - frontend_network
    volumes:
      - ./frontend:/app
    restart: unless-stopped

  frontend_prod:
    build:
      context: ./frontend
      target: production
      args:
        VUE_APP_ENV: ${ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
      - VUE_APP_ENV=${ENV}
    ports:
      - "${FRONTEND_PORT}:${SERVER_FRONTEND_PORT}"
    depends_on:
      - backend_prod
    networks:
      - frontend_network
    restart: unless-stopped

volumes:
  app_prod_postgres_data:
    external: true

networks:
  frontend_network:
  backend_network:
