# Generated by Django 4.1.10 on 2023-09-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailAssistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_provider',
            field=models.CharField(default='Gmail', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='provider_id',
            field=models.CharField(default='Gmail', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
