# Generated by Django 4.1.10 on 2023-09-18 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MailAssistant', '0002_message_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Senders',
            fields=[
                ('id_sender', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50)),
                ('paswd', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id_rule', models.AutoField(primary_key=True, serialize=False)),
                ('info_AI', models.TextField()),
                ('priority', models.CharField(max_length=50)),
                ('block', models.BooleanField()),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MailAssistant.categories')),
                ('id_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MailAssistant.senders')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MailAssistant.users')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id_preferences', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.CharField(max_length=50)),
                ('bg_color', models.CharField(max_length=200)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MailAssistant.users')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id_email', models.AutoField(primary_key=True, serialize=False)),
                ('email_short_summary', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('subject', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('read', models.BooleanField()),
                ('answer_later', models.BooleanField()),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MailAssistant.categories')),
                ('id_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_emails', to='MailAssistant.senders')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MailAssistant.users')),
            ],
        ),
        migrations.CreateModel(
            name='CC',
            fields=[
                ('id_cc', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('id_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MailAssistant.email')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MailAssistant.users'),
        ),
        migrations.CreateModel(
            name='BulletPoints',
            fields=[
                ('id_bullet_point', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('id_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MailAssistant.email')),
            ],
        ),
    ]
