# Generated by Django 4.1.10 on 2024-01-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailAssistant', '0003_credsapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialapi',
            name='email',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.DeleteModel(
            name='CredsAPI',
        ),
    ]
