# Generated by Django 4.1.10 on 2023-09-20 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MailAssistant', '0003_categories_senders_users_rules_preferences_email_cc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='email',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='id_user',
        ),
        migrations.AddField(
            model_name='categories',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_user_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preferences',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rules',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
