# Generated by Django 4.1.10 on 2024-01-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MailAssistant', '0004_socialapi_email_delete_credsapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialapi',
            name='email',
            field=models.CharField(max_length=320, null=True),
        ),
    ]
