# Generated by Django 4.1.10 on 2024-01-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MailAssistant', '0005_sender_user'),
        ('MailAssistant', '0006_alter_socialapi_access_token_and_more'),
    ]

    operations = [
    ]
