export const knownProviders = [
    {
        name: "Fastmail",
        link: "https://app.fastmail.com/settings/security/apps/new",
        imapHost: "imap.fastmail.com",
        imapPort: 993,
        imapSsl: true,
        smtpHost: "smtp.fastmail.com",
        smtpPort: 465,
        smtpSsl: true,
    },
    {
        name: "GMX",
        link: "https://support.gmx.com/pop-imap/toggle.html",
        imapHost: "imap.gmx.com",
        imapPort: 993,
        imapSsl: true,
        smtpHost: "mail.gmx.com",
        smtpPort: 465,
        smtpSsl: true,
    },
    {
        name: "Orange",
        link: "https://assistance.orange.fr/ordinateurs-peripheriques/installer-et-utiliser/l-utilisation-du-mail-et-du-cloud/mail-orange/le-mail-orange-nouvelle-version/parametrer-la-boite-mail/mail-orange-comment-acceder-a-sa-boite-mail-orange-depuis-une-application-ou-un-logiciel-de-messagerie-non-fourni-par-orange_434630-964290#onglet1",
        imapHost: "imap.orange.fr",
        imapPort: 993,
        imapSsl: true,
        smtpHost: "smtp.orange.fr",
        smtpPort: 465,
        smtpSsl: true,
    },
    {
        name: "Microsoft",
        link: "",
        imapHost: "",
        imapPort: 0,
        imapSsl: true,
        smtpHost: "",
        smtpPort: 0,
        smtpSsl: true,
    },
    {
        name: "Google",
        link: "https://myaccount.google.com/u/1/apppasswords",
        imapHost: "imap.gmail.com",
        imapPort: 993,
        imapSsl: true,
        smtpHost: "smtp.gmail.com",
        smtpPort: 587,
        smtpSsl: true,
    },
    {
        name: "Yahoo",
        link: "",
        imapHost: "",
        imapPort: 0,
        imapSsl: true,
        smtpHost: "",
        smtpPort: 0,
        smtpSsl: true,
    },
    {
        name: "Apple",
        link: "",
        imapHost: "",
        imapPort: 0,
        imapSsl: true,
        smtpHost: "",
        smtpPort: 0,
        smtpSsl: true,
    },
    {
        name: "Other",
        link: "",
        imapHost: "",
        imapPort: 0,
        imapSsl: true,
        smtpHost: "",
        smtpPort: 0,
        smtpSsl: true,
    },
];
