# Generated by Django 5.1.6 on 2025-02-08 22:20

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aomail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=255)),
                ('agent_ai_model', models.CharField(max_length=255)),
                ('ai_template', models.TextField(blank=True, null=True)),
                ('email_example', models.TextField(blank=True, null=True)),
                ('length', models.CharField(max_length=50)),
                ('formality', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('last_used', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/agent_icon/')),
                ('icon_name', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=320, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('provider_id', models.CharField(max_length=320, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=200, unique=True)),
                ('email_provider', models.CharField(max_length=50)),
                ('short_summary', models.TextField()),
                ('one_line_summary', models.CharField(max_length=1000)),
                ('html_content', models.TextField(default='')),
                ('subject', models.CharField(max_length=800)),
                ('priority', models.CharField(max_length=50)),
                ('read', models.BooleanField(default=False)),
                ('read_date', models.DateTimeField(default=None, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('answer_later', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('answer', models.CharField(max_length=50)),
                ('relevance', models.CharField(max_length=50)),
                ('spam', models.BooleanField(default=False)),
                ('scam', models.BooleanField(default=False)),
                ('newsletter', models.BooleanField(default=False)),
                ('notification', models.BooleanField(default=False)),
                ('meeting', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aomail.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_emails', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_emails', to='aomail.sender')),
            ],
        ),
        migrations.CreateModel(
            name='CC_sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_senders', to='aomail.email')),
            ],
        ),
        migrations.CreateModel(
            name='BCC_sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bcc_senders', to='aomail.email')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_api', models.CharField(max_length=500)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='aomail.email')),
            ],
        ),
        migrations.CreateModel(
            name='KeyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reply', models.BooleanField()),
                ('position', models.IntegerField(default=None, null=True)),
                ('category', models.TextField(max_length=50)),
                ('organization', models.TextField(max_length=50)),
                ('topic', models.TextField(max_length=50)),
                ('content', models.TextField(max_length=50)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aomail.email')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('platform', models.CharField(max_length=50)),
                ('carrier', models.CharField(max_length=50)),
                ('label_name', models.CharField(max_length=250)),
                ('postage_deadline', models.DateTimeField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aomail.email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_labels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MicrosoftListener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=320)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_mail', to='aomail.email')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('theme', models.CharField(default='light', max_length=50)),
                ('language', models.CharField(default='american', max_length=50)),
                ('important_guidelines', models.CharField(default="if it's strictly work-related AND either urgent or requires prompt business action", max_length=1000)),
                ('informative_guidelines', models.CharField(default="if it's strictly work-related AND contains company updates or non-urgent team info", max_length=1000)),
                ('useless_guidelines', models.CharField(default="it's promotional OR newsletter content (like TV shows, marketing emails, subscriptions)", max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_operator', models.CharField(default='AND', max_length=3)),
                ('domains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None)),
                ('sender_emails', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None)),
                ('has_attachements', models.BooleanField(null=True)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None)),
                ('priorities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None)),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None)),
                ('relevances', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None)),
                ('flags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None)),
                ('email_deal_with', models.CharField(max_length=1000, null=True)),
                ('action_transfer_recipients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None)),
                ('action_set_flags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None)),
                ('action_mark_as', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None)),
                ('action_delete', models.BooleanField(null=True)),
                ('action_set_priority', models.CharField(max_length=30, null=True)),
                ('action_set_relevance', models.CharField(max_length=30, null=True)),
                ('action_set_answer', models.CharField(max_length=30, null=True)),
                ('action_reply_prompt', models.CharField(max_length=1000, null=True)),
                ('action_reply_recipients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), null=True, size=None)),
                ('action_set_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aomail.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_api', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=524, unique=True)),
                ('access_token', models.CharField(max_length=3000)),
                ('refresh_token', models.CharField(max_length=2000)),
                ('user_description', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
                ('social_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='aomail.socialapi')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleListener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(null=True)),
                ('social_api', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_api_google_listener', to='aomail.socialapi')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('important', models.BooleanField(default=False)),
                ('informative', models.BooleanField(default=False)),
                ('useless', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('spam', models.BooleanField(default=False)),
                ('scam', models.BooleanField(default=False)),
                ('newsletter', models.BooleanField(default=False)),
                ('notification', models.BooleanField(default=False)),
                ('meeting', models.BooleanField(default=False)),
                ('relevance', models.CharField(default=True, max_length=50, null=True)),
                ('answer', models.CharField(default=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aomail.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('social_api', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aomail.socialapi')),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='social_api',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_api_emails', to='aomail.socialapi'),
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_emails_received', models.IntegerField(default=0)),
                ('nb_emails_important', models.IntegerField(default=0)),
                ('nb_emails_informative', models.IntegerField(default=0)),
                ('nb_emails_useless', models.IntegerField(default=0)),
                ('nb_tokens_input', models.IntegerField(default=0)),
                ('nb_tokens_output', models.IntegerField(default=0)),
                ('nb_answer_required', models.IntegerField(default=0)),
                ('nb_might_require_answer', models.IntegerField(default=0)),
                ('nb_no_answer_required', models.IntegerField(default=0)),
                ('nb_highly_relevant', models.IntegerField(default=0)),
                ('nb_possibly_relevant', models.IntegerField(default=0)),
                ('nb_not_relevant', models.IntegerField(default=0)),
                ('nb_spam', models.IntegerField(default=0)),
                ('nb_scam', models.IntegerField(default=0)),
                ('nb_newsletter', models.IntegerField(default=0)),
                ('nb_notification', models.IntegerField(default=0)),
                ('nb_meeting', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('subscription_id', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=True)),
                ('is_block', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
