# Generated by Django 5.1.6 on 2025-02-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aomail', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='action_reply_recipients',
        ),
    ]