# Generated by Django 5.1.6 on 2025-02-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aomail', '0003_remove_rule_action_reply_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='llm_provider',
            field=models.CharField(default='google', max_length=50),
        ),
        migrations.AddField(
            model_name='preference',
            name='llm_model',
            field=models.CharField(max_length=50, null=True),
        ),
    ]