# Generated by Django 5.1.6 on 2025-03-06 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aomail', '0005_preference_categorize_and_summarize_email_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_password', models.CharField(max_length=2000)),
                ('host', models.CharField(max_length=30)),
                ('port', models.IntegerField()),
                ('encryption', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='socialapi',
            name='imap_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imap_config', to='aomail.emailserverconfig'),
        ),
        migrations.AddField(
            model_name='socialapi',
            name='smtp_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smtp_config', to='aomail.emailserverconfig'),
        ),
    ]
