# Generated by Django 5.1.6 on 2025-03-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aomail', '0006_emailserverconfig_socialapi_imap_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialapi',
            name='last_fetched_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
