name: Run AI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-ai-tests:
    strategy:
      fail-fast: false

    name: Run AI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install google-generativeai
 
      - name: Setup DJANGO_SETTINGS_MODULE
        run: |
          export DJANGO_SETTINGS_MODULE=config.settings

      - name: Run tests
        run: python -m pytest
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}