name: Run AI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-ai-tests:
    strategy:
      fail-fast: false

    name: Run AI Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
 
      - name: Run tests
        run: |
          export DJANGO_SETTINGS_MODULE=config.settings
          python -m pytest
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}